spring:
  liquibase:
    #数据库初始化开关，第一次启动开启
    enabled: true
    #初始化脚本路径
    change-log: classpath:/db/changelog/master.xml
  #数据源
  datasource:
    #数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://10.10.200.32:3306/szls?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    # 自定义表单数据库
    db-name: szls
    #数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    #数据库用户名
    username: root
    #数据库密码
    password: 1qaz@WSX3edc

  application:
    name: sr-digitalwin
    aliasname: 数字孪生

  cloud:
    nacos:
      discovery:
        server-addr: http://10.10.200.60:8848
        ip: 10.10.200.60
        port: 8988
register:
  url: http://10.10.200.60:8848
#    password: 1qaz@WSX
# 自定义表单模板目录
ctsi:
  upload:
    uploadPath: /Users/lijie/upload



