spring:
  liquibase:
    #数据库初始化开关，第一次启动开启
    enabled: true
    #初始化脚本路径
    change-log: classpath:/db/changelog/master.xml
  #数据源
  datasource:
    #数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://117.80.227.57:3306/szls?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    # 自定义表单数据库
    db-name: sr
    #数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    #数据库用户名
    username: user001
    #数据库密码
    password: D#r2K2bR
#    password: srxx@2023

  application:
    name: sr-digitalwin
    aliasname: 数字孪生

  cloud:
    nacos:
      discovery:
        server-addr: http://kqtest.cloudsid.cn:8848
#        ip: 192.168.31.43
#        port: 7115
register:
  url:http://kqtest.cloudsid.cn:8848
#    password: 1qaz@WSX
# 自定义表单模板目录
ctsi:
  upload:
    uploadPath: /Users/lijie/upload


