package com.ctsi.ssdc.project.repository;


import com.ctsi.ssdc.project.domain.SrGradeInfo;
import com.ctsi.ssdc.project.domain.SrGradeInfoExample;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;


/**
 * SrGradeInfoSqlProvider
 *
 * @author hx
 * @date 2023-06-09 10:18:29
*/

public class SrGradeInfoSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String countByExample(SrGradeInfoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("sr_grade_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String deleteByExample(SrGradeInfoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("sr_grade_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String insertSelective(SrGradeInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("sr_grade_info");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        if (record.getSchool() != null) {
            sql.VALUES("school", "#{school,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.VALUES("create_by", "#{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getUpdateBy() != null) {
            sql.VALUES("update_by", "#{updateBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String selectByExample(SrGradeInfoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("name");
        sql.SELECT("school");
        sql.SELECT("remark");
        sql.SELECT("create_by");
        sql.SELECT("create_time");
        sql.SELECT("update_by");
        sql.SELECT("update_time");
        sql.FROM("sr_grade_info");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        SrGradeInfo record = (SrGradeInfo) parameter.get("record");
        SrGradeInfoExample example = (SrGradeInfoExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("sr_grade_info");

        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getName() != null) {
        sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        if (record.getSchool() != null) {
        sql.SET("school = #{school,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
        sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
        sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
        sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getUpdateBy() != null) {
        sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
        sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("sr_grade_info");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("name = #{name,jdbcType=VARCHAR}");
        sql.SET("school = #{school,jdbcType=VARCHAR}");
        sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");

        SrGradeInfoExample example = (SrGradeInfoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    public String updateByPrimaryKeySelective(SrGradeInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("sr_grade_info");

        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        if (record.getSchool() != null) {
            sql.SET("school = #{school,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     */
    protected void applyWhere(SQL sql, SrGradeInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<SrGradeInfoExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            SrGradeInfoExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<SrGradeInfoExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    SrGradeInfoExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
