package com.ctsi.ssdc.project.repository;


import com.ctsi.ssdc.project.domain.GradeReport;
import com.ctsi.ssdc.project.domain.SrGradeInfo;
import com.ctsi.ssdc.project.domain.SrGradeInfoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

/**
 * SrGradeInfoRepository
 *
 * @author hx
 * @date 2023-06-09 10:18:29
 */

@Mapper
public interface SrGradeInfoRepository extends com.ctsi.ssdc.repository.BaseRepository<SrGradeInfo, Long, SrGradeInfoExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @SelectProvider(type=SrGradeInfoSqlProvider.class, method="countByExample")
    @Override
    long countByExample(SrGradeInfoExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @DeleteProvider(type=SrGradeInfoSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(SrGradeInfoExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @Delete({
            "delete from sr_grade_info",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     *
     * @date 2023-06-09 10:18:29
     */
    @Insert({
            "insert into sr_grade_info (",
            "id,",
            "name,",
            "school,",
            "remark,",
            "create_by,",
            "create_time,",
            "update_by,",
            "update_time",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{name,jdbcType=VARCHAR}, ",
            "#{school,jdbcType=VARCHAR}, ",
            "#{remark,jdbcType=VARCHAR}, ",
            "#{createBy,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=TIMESTAMP}, ",
            "#{updateBy,jdbcType=VARCHAR}, ",
            "#{updateTime,jdbcType=TIMESTAMP}",

            ")"

    })
    @Override
    int insert(SrGradeInfo record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @InsertProvider(type=SrGradeInfoSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(SrGradeInfo record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @SelectProvider(type=SrGradeInfoSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
            @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_by", property="createBy", jdbcType=JdbcType.BIGINT),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })

    @Override
    List<SrGradeInfo> selectByExample(SrGradeInfoExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @Select({
            "select",
            "id,",
            "name,",
            "school,",
            "remark,",
            "create_by,",
            "create_time,",
            "update_by,",
            "update_time",
            "from sr_grade_info",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
            @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_by", property="createBy", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    @Override
    SrGradeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @UpdateProvider(type=SrGradeInfoSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") SrGradeInfo record, @Param("example") SrGradeInfoExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @UpdateProvider(type=SrGradeInfoSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") SrGradeInfo record, @Param("example") SrGradeInfoExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     *@date 2023-06-09 10:18:29
     */
    @UpdateProvider(type=SrGradeInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(SrGradeInfo record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sr_grade_info
     *
     * @date 2023-06-09 10:18:29
     */
    @Update({
            "update sr_grade_info",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "name = #{name,jdbcType=VARCHAR},",
            "school = #{school,jdbcType=VARCHAR},",
            "remark = #{remark,jdbcType=VARCHAR},",
            "create_by = #{createBy,jdbcType=BIGINT},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_by = #{updateBy,jdbcType=BIGINT},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(SrGradeInfo record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from sr_grade_info where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


    @Select("select * from sr_grade_info where school = '${school}'")
    public List<SrGradeInfo> getGradeBySchool(@Param("school") String school);

    @Select("select * from sr_grade_info where school = '${school}' and  name = '${name}'")
    public SrGradeInfo getExistGrade(@Param("school") String school,@Param("name") String name);

    @Select("select b.name as gradeName,count(1) as gradeNum from sr_class_info a,sr_grade_info b " +
            "where b.school='${school}' and a.grade_id = b.id group by a.grade_id ")
    public List<GradeReport> getGradeRepport(String school);


}





